# Generated by Django 5.0.8 on 2024-11-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='location',
            new_name='geom',
        ),
    ]
