# Generated by Django 5.0.14 on 2026-01-25 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fieldwork_options_remove_fieldwork_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='project',
            name='is_active',
        ),
    ]
