# Generated by Django 5.0.8 on 2024-11-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_location_project_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationstatus',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.location'),
        ),
    ]
