# Generated by Django 5.0.8 on 2025-02-19 17:40

import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_locationstatus_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='location',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.CreateModel(
            name='Fieldwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('weather', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldwork', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldwork', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fieldwork',
            },
        ),
        migrations.CreateModel(
            name='LocationVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('needs-maintenance', 'Needs maintenance'), ('decommissioned', 'Decommissioned'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('fieldwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_visits', to='core.fieldwork')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='core.location')),
            ],
            options={
                'verbose_name_plural': "Locations' statuses",
            },
        ),
        migrations.DeleteModel(
            name='LocationStatus',
        ),
    ]
