# Generated by Django 5.0.14 on 2026-01-27 09:39

import django.db.models.deletion
import simple_history.models
import watersync.core.generics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historicalproject_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LakeDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lake_detail', serialize=False, to='core.location')),
                ('depth', models.FloatField(blank=True, help_text='Maximum depth of the lake in meters', null=True, verbose_name='Depth (m)')),
                ('area', models.FloatField(blank=True, help_text='Surface area of the lake in square meters', null=True, verbose_name='Area (m²)')),
                ('volume', models.FloatField(blank=True, help_text='Total volume of the lake in cubic meters', null=True, verbose_name='Volume (m³)')),
                ('water_quality', models.CharField(blank=True, help_text='e.g. Clear, Murky', max_length=100, null=True, verbose_name='Water Quality')),
            ],
            options={
                'verbose_name': 'Lake Detail',
                'verbose_name_plural': 'Lake Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.CreateModel(
            name='PiezometerDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='piezometer_detail', serialize=False, to='core.location')),
                ('depth', models.FloatField(help_text='Total depth of the piezometer below ground level in meters', verbose_name='Total depth below ground (m)')),
                ('casing_top', models.FloatField(help_text='Height of the casing top relative to ground level', verbose_name='Top of Piezometer below (-)/above ground (+) (m)')),
                ('screen_top', models.FloatField(help_text='Depth to the top of the screen section below ground', verbose_name='Top of Screen below ground (+) (m)')),
                ('screen_bottom', models.FloatField(help_text='Depth to the bottom of the screen section below ground', verbose_name='Bottom of Screen below ground (+) (m)')),
                ('drill_type', models.CharField(choices=[('hand_auger', 'Hand Auger'), ('direct_push', 'Direct Push'), ('rotary_drilling', 'Rotary Drilling'), ('sonic_rig', 'Sonic Rig'), ('other', 'Other')], max_length=20, verbose_name='Drill Type')),
                ('profile_description', models.TextField(blank=True, help_text='e.g. Sandy, Clayey', null=True, verbose_name='Profile Description')),
                ('diameter', models.FloatField(help_text='Internal diameter of the piezometer in millimeters', verbose_name='Diameter (mm)')),
                ('material', models.CharField(choices=[('pvc', 'PVC'), ('steel', 'Steel'), ('other', 'Other')], max_length=20, verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Piezometer Detail',
                'verbose_name_plural': 'Piezometer Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.CreateModel(
            name='PrecipitationDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='precipitation_detail', serialize=False, to='core.location')),
                ('intensity', models.FloatField(blank=True, help_text='Rainfall intensity in millimeters per hour', null=True, verbose_name='Intensity (mm/h)')),
                ('duration', models.IntegerField(blank=True, help_text='Duration of precipitation event in minutes', null=True, verbose_name='Duration (minutes)')),
            ],
            options={
                'verbose_name': 'Precipitation Detail',
                'verbose_name_plural': 'Precipitation Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.CreateModel(
            name='PumpingWellDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pumping_well_detail', serialize=False, to='core.location')),
                ('pumping_rate', models.FloatField(blank=True, help_text='Pumping rate in cubic meters per hour', null=True, verbose_name='Pumping Rate (m³/h)')),
            ],
            options={
                'verbose_name': 'Pumping Well Detail',
                'verbose_name_plural': 'Pumping Well Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.CreateModel(
            name='RiverDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='river_detail', serialize=False, to='core.location')),
                ('width', models.FloatField(blank=True, help_text='Width of the river at the measurement point in meters', null=True, verbose_name='Width (m)')),
                ('depth', models.FloatField(blank=True, help_text='Depth of the river at the measurement point in meters', null=True, verbose_name='Depth (m)')),
                ('flow_rate', models.FloatField(blank=True, help_text='Flow rate of the river in cubic meters per second', null=True, verbose_name='Flow rate (m³/s)')),
            ],
            options={
                'verbose_name': 'River Detail',
                'verbose_name_plural': 'River Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.CreateModel(
            name='WastewaterDetail',
            fields=[
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wastewater_detail', serialize=False, to='core.location')),
                ('number_of_tanks', models.IntegerField(blank=True, null=True, verbose_name='Number of tanks')),
                ('treatment_level', models.IntegerField(blank=True, help_text='Treatment level indicator', null=True, verbose_name='Treatment level')),
            ],
            options={
                'verbose_name': 'Wastewater Detail',
                'verbose_name_plural': 'Wastewater Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='location',
            name='detail',
        ),
        migrations.CreateModel(
            name='HistoricalLakeDetail',
            fields=[
                ('depth', models.FloatField(blank=True, help_text='Maximum depth of the lake in meters', null=True, verbose_name='Depth (m)')),
                ('area', models.FloatField(blank=True, help_text='Surface area of the lake in square meters', null=True, verbose_name='Area (m²)')),
                ('volume', models.FloatField(blank=True, help_text='Total volume of the lake in cubic meters', null=True, verbose_name='Volume (m³)')),
                ('water_quality', models.CharField(blank=True, help_text='e.g. Clear, Murky', max_length=100, null=True, verbose_name='Water Quality')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical Lake Detail',
                'verbose_name_plural': 'historical Lake Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPiezometerDetail',
            fields=[
                ('depth', models.FloatField(help_text='Total depth of the piezometer below ground level in meters', verbose_name='Total depth below ground (m)')),
                ('casing_top', models.FloatField(help_text='Height of the casing top relative to ground level', verbose_name='Top of Piezometer below (-)/above ground (+) (m)')),
                ('screen_top', models.FloatField(help_text='Depth to the top of the screen section below ground', verbose_name='Top of Screen below ground (+) (m)')),
                ('screen_bottom', models.FloatField(help_text='Depth to the bottom of the screen section below ground', verbose_name='Bottom of Screen below ground (+) (m)')),
                ('drill_type', models.CharField(choices=[('hand_auger', 'Hand Auger'), ('direct_push', 'Direct Push'), ('rotary_drilling', 'Rotary Drilling'), ('sonic_rig', 'Sonic Rig'), ('other', 'Other')], max_length=20, verbose_name='Drill Type')),
                ('profile_description', models.TextField(blank=True, help_text='e.g. Sandy, Clayey', null=True, verbose_name='Profile Description')),
                ('diameter', models.FloatField(help_text='Internal diameter of the piezometer in millimeters', verbose_name='Diameter (mm)')),
                ('material', models.CharField(choices=[('pvc', 'PVC'), ('steel', 'Steel'), ('other', 'Other')], max_length=20, verbose_name='Material')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical Piezometer Detail',
                'verbose_name_plural': 'historical Piezometer Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPrecipitationDetail',
            fields=[
                ('intensity', models.FloatField(blank=True, help_text='Rainfall intensity in millimeters per hour', null=True, verbose_name='Intensity (mm/h)')),
                ('duration', models.IntegerField(blank=True, help_text='Duration of precipitation event in minutes', null=True, verbose_name='Duration (minutes)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical Precipitation Detail',
                'verbose_name_plural': 'historical Precipitation Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPumpingWellDetail',
            fields=[
                ('pumping_rate', models.FloatField(blank=True, help_text='Pumping rate in cubic meters per hour', null=True, verbose_name='Pumping Rate (m³/h)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical Pumping Well Detail',
                'verbose_name_plural': 'historical Pumping Well Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRiverDetail',
            fields=[
                ('width', models.FloatField(blank=True, help_text='Width of the river at the measurement point in meters', null=True, verbose_name='Width (m)')),
                ('depth', models.FloatField(blank=True, help_text='Depth of the river at the measurement point in meters', null=True, verbose_name='Depth (m)')),
                ('flow_rate', models.FloatField(blank=True, help_text='Flow rate of the river in cubic meters per second', null=True, verbose_name='Flow rate (m³/s)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical River Detail',
                'verbose_name_plural': 'historical River Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalWastewaterDetail',
            fields=[
                ('number_of_tanks', models.IntegerField(blank=True, null=True, verbose_name='Number of tanks')),
                ('treatment_level', models.IntegerField(blank=True, help_text='Treatment level indicator', null=True, verbose_name='Treatment level')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
            ],
            options={
                'verbose_name': 'historical Wastewater Detail',
                'verbose_name_plural': 'historical Wastewater Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
