# Generated by Django 5.0.8 on 2025-02-19 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_location_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvisit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vists', to='core.location'),
        ),
    ]
