# Generated by Django 5.0.8 on 2025-02-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_locationvisit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvisit',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.location'),
        ),
    ]
