# Generated by Django 5.0.8 on 2025-02-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_locationvisit_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldwork',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fieldworks', to='core.project'),
        ),
        migrations.AlterField(
            model_name='locationvisit',
            name='fieldwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.fieldwork'),
        ),
    ]
