# Generated by Django 5.0.8 on 2025-02-21 09:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_fieldwork_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldwork',
            name='user',
        ),
        migrations.AddField(
            model_name='fieldwork',
            name='users',
            field=models.ManyToManyField(related_name='fieldworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
