# Generated by Django 5.0.8 on 2025-03-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_fieldwork_user_fieldwork_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldwork',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={},
        ),
        migrations.AlterModelOptions(
            name='locationvisit',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
