# Generated by Django 5.0.8 on 2025-03-21 14:52

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_project_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='geom_poly',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
