# Generated by Django 5.0.8 on 2025-03-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_project_geom_poly_alter_project_geom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldwork',
            old_name='users',
            new_name='user',
        ),
    ]
