# Generated by Django 5.0.8 on 2025-03-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_locationvisit_fieldwork'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicallocation',
            old_name='added_by',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='added_by',
            new_name='user',
        ),
    ]
