# Generated by Django 5.0.8 on 2025-03-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_project_options_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalLocation',
        ),
    ]
