# Generated by Django 5.0.8 on 2025-03-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historicallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldwork',
            old_name='comment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='locationvisit',
            name='comment',
        ),
        migrations.AddField(
            model_name='locationvisit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
