# Generated by Django 5.0.8 on 2025-04-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_locationvisit_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvisit',
            name='slug',
        ),
        migrations.AddField(
            model_name='locationvisit',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
