# Generated by Django 5.0.8 on 2025-04-15 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_locationvisit_slug_locationvisit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationvisit',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 4, 15, 14, 24, 4, 95116, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
