# Generated by Django 5.0.8 on 2025-04-19 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvisit',
            name='date',
        ),
        migrations.AlterField(
            model_name='locationvisit',
            name='fieldwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='core.fieldwork'),
            preserve_default=False,
        ),
    ]
