# Generated by Django 5.0.8 on 2025-06-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_locationvisit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldwork',
            name='weather',
            field=models.CharField(choices=[('sunny', 'Sunny'), ('cloudy', 'Cloudy'), ('rainy', 'Rainy'), ('snowy', 'Snowy'), ('windy', 'Windy'), ('stormy', 'Stormy')], default='sunny', max_length=20),
        ),
    ]
