# Generated by Django 5.0.8 on 2025-07-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_fieldwork_weather'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
