# Generated by Django 5.0.8 on 2025-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_historicallocation_user_remove_location_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldwork',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='locationvisit',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('needs-maintenance', 'Needs Maintenance'), ('decommissioned', 'Decommissioned'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
    ]
