# Generated by Django 5.0.8 on 2025-07-04 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_fieldwork_date_alter_locationvisit_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created',
        ),
        migrations.RemoveField(
            model_name='location',
            name='modified',
        ),
    ]
