# Generated by Django 5.0.8 on 2025-07-04 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_historicallocation_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='modified',
        ),
    ]
