# Generated by Django 5.0.8 on 2025-08-08 11:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_historicalproject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldwork',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='fieldworks', to=settings.AUTH_USER_MODEL),
        ),
    ]
