# Generated by Django 5.0.8 on 2025-08-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_fieldwork_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallocation',
            name='decommision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='decommision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
