# Generated by Django 5.0.8 on 2025-08-12 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_historicallocation_decommision_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallocation',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='altitude',
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('needs-maintenance', 'Needs Maintenance'), ('decommissioned', 'Decommissioned'), ('unknown', 'Unknown')], default='operational', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='status',
            field=models.CharField(choices=[('operational', 'Operational'), ('needs-maintenance', 'Needs Maintenance'), ('decommissioned', 'Decommissioned'), ('unknown', 'Unknown')], default='operational', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='type',
            field=models.CharField(choices=[('pumping_well', 'Pumping well'), ('piezometer', 'Piezometer'), ('river', 'River'), ('lake', 'Lake'), ('wastewater', 'Wastewater'), ('precipitation', 'Precipitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(dim=3, srid=4326),
        ),
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('pumping_well', 'Pumping well'), ('piezometer', 'Piezometer'), ('river', 'River'), ('lake', 'Lake'), ('wastewater', 'Wastewater'), ('precipitation', 'Precipitation')], max_length=20),
        ),
    ]
