# Generated by Django 5.0.8 on 2025-08-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_historicallocation_altitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationvisit',
            name='fieldwork',
        ),
        migrations.RemoveField(
            model_name='locationvisit',
            name='location',
        ),
    ]
