# Generated by Django 5.0.8 on 2025-08-12 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_locationvisit_fieldwork_and_more'),
        ('groundwater', '0007_remove_gwlmanualmeasurement_location_visit_and_more'),
        ('waterquality', '0018_remove_sample_location_visit_sample_fieldwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationVisit',
        ),
    ]
