# Generated by Django 5.0.8 on 2024-11-12 00:58

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('sample_collection', models.TextField(blank=True, null=True)),
                ('sample_preservation', models.TextField(blank=True, null=True)),
                ('sample_storage', models.TextField(blank=True, null=True)),
                ('analytical_method', models.TextField(blank=True, null=True)),
                ('data_postprocessing', models.TextField(blank=True, null=True)),
                ('standard_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_parameters', models.CharField(blank=True, max_length=50, null=True)),
                ('container_type', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_collected', models.FloatField(blank=True, null=True)),
                ('replica_number', models.IntegerField(blank=True, default=0, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterquality.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('parameter_name', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('measured_on', models.DateTimeField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='waterquality.sample')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SamplingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('executed_at', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('executed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_events', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sampling_events', to='core.location')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sample',
            name='sampling_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='waterquality.samplingevent'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('sampling_event', 'target_parameters', 'replica_number')},
        ),
    ]
