# Generated by Django 5.0.14 on 2026-01-20 10:13

import django.db.models.deletion
import watersync.core.generics.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParameterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=100, unique=True)),
                ('method_name', models.CharField(max_length=100)),
                ('sample_collection', models.TextField(blank=True, null=True)),
                ('sample_preservation', models.TextField(blank=True, null=True)),
                ('sample_storage', models.TextField(blank=True, null=True)),
                ('analytical_method', models.TextField(blank=True, null=True)),
                ('data_postprocessing', models.TextField(blank=True, null=True)),
                ('standard_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterquality.parametergroup')),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_on', models.DateField(blank=True, null=True)),
                ('container_type', models.CharField(blank=True, max_length=50, null=True)),
                ('volume_collected', models.FloatField(blank=True, null=True)),
                ('replica_number', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_external', models.BooleanField(default=False)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('fieldwork', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.fieldwork')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.location')),
                ('parameter_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waterquality.parametergroup')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterquality.protocol')),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_data', models.JSONField(help_text='JSON field storing measurement value and unit information')),
                ('detection_limit_data', models.JSONField(blank=True, help_text='JSON field storing detection limit value and unit information', null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waterquality.parameter')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='waterquality.sample')),
            ],
            options={
                'unique_together': {('sample', 'parameter')},
            },
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
    ]
