# Generated by Django 5.0.14 on 2026-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='parameter',
            field=models.CharField(help_text='The parameter measured', max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='parameter_group',
            field=models.CharField(help_text='The group of parameters targeted for analysis', max_length=50),
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='detection_limit_data',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measurement_data',
        ),
        migrations.AddField(
            model_name='measurement',
            name='detection_limit',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='The detection limit value (same unit as measurement)', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='unit',
            field=models.CharField(default='mg/L', help_text='The unit of measurement', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=10, default=0, help_text='The measured value', max_digits=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='ParameterGroup',
        ),
    ]
