# Generated by Django 5.0.8 on 2024-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
