# Generated by Django 5.0.8 on 2025-04-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location_visit',
        ),
    ]
