# Generated by Django 5.0.8 on 2024-08-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('waterquality', '0002_alter_sample_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='waterquality.sample'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='samples', to='core.location'),
        ),
    ]
