# Generated by Django 5.0.8 on 2025-04-02 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_locationvisit_slug'),
        ('waterquality', '0002_remove_sample_location_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='location_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.locationvisit'),
            preserve_default=False,
        ),
    ]
