# Generated by Django 5.0.8 on 2024-12-13 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_locationstatus_location'),
        ('waterquality', '0002_protocol_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplingevent',
            name='executed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplingevents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='samplingevent',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samplingevents', to='core.location'),
        ),
    ]
