# Generated by Django 5.0.14 on 2026-01-21 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0002_alter_measurement_parameter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='field_sample',
            field=models.ForeignKey(blank=True, help_text='Link to the field measurement sample (PARAMS) taken at the same time/location', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_samples', to='waterquality.sample'),
        ),
    ]
