# Generated by Django 5.0.8 on 2025-04-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0003_sample_location_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='details',
            new_name='description',
        ),
        migrations.AddField(
            model_name='measurement',
            name='detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
