# Generated by Django 5.0.8 on 2024-08-29 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0003_alter_measurement_sample_alter_sample_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
