# Generated by Django 5.0.8 on 2025-04-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0005_sample_date_sample_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='detail',
        ),
    ]
