# Generated by Django 5.0.8 on 2024-12-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0005_alter_measurement_measured_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='replica_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='target_parameters',
            field=models.CharField(max_length=50),
        ),
    ]
