# Generated by Django 5.0.8 on 2024-12-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0006_alter_sample_replica_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='target_parameters',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
