# Generated by Django 5.0.8 on 2025-04-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0006_remove_sample_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='detail',
        ),
    ]
