# Generated by Django 5.0.8 on 2025-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0007_remove_measurement_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='date',
            new_name='collected_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='measured_on',
        ),
        migrations.AddField(
            model_name='sample',
            name='measured_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
