# Generated by Django 5.0.8 on 2024-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0007_alter_sample_target_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='target_parameters',
            field=models.CharField(max_length=50),
        ),
    ]
