# Generated by Django 5.0.8 on 2025-04-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0008_rename_date_sample_collected_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetParameterGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='sample',
            name='collected_at',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='location',
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterquality.targetparametergroup')),
            ],
        ),
    ]
