# Generated by Django 5.0.8 on 2025-04-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0009_targetparametergroup_remove_sample_collected_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetparametergroup',
            name='code',
            field=models.CharField(default='', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
