# Generated by Django 5.0.8 on 2025-04-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0010_targetparametergroup_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TargetParameterGroup',
            new_name='ParameterGroup',
        ),
    ]
