# Generated by Django 5.0.8 on 2025-04-24 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0011_rename_targetparametergroup_parametergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='target_parameters',
        ),
        migrations.AddField(
            model_name='sample',
            name='parameter_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='waterquality.parametergroup'),
            preserve_default=False,
        ),
    ]
