# Generated by Django 5.0.8 on 2025-04-24 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_locationvisit_date_and_more'),
        ('waterquality', '0012_remove_sample_target_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='waterquality.parameter'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.unit'),
        ),
    ]
