# Generated by Django 5.0.8 on 2025-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0013_alter_measurement_parameter_alter_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='measured_at',
            new_name='measured_on',
        ),
    ]
