# Generated by Django 5.0.8 on 2025-06-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0014_rename_measured_at_sample_measured_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocol',
            name='user',
        ),
    ]
