# Generated by Django 5.0.8 on 2025-07-04 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_historicalproject'),
        ('waterquality', '0015_remove_protocol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='location_visit',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.locationvisit'),
            preserve_default=False,
        ),
    ]
