# Generated by Django 5.0.8 on 2025-08-11 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_fieldwork_user'),
        ('waterquality', '0016_alter_sample_location_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='code',
            field=models.CharField(default='CODE', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.location'),
        ),
        migrations.AddField(
            model_name='sample',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='location_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.locationvisit'),
        ),
    ]
