# Generated by Django 5.0.8 on 2025-08-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_locationvisit_fieldwork_and_more'),
        ('waterquality', '0017_parameter_code_sample_date_sample_is_external_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='location_visit',
        ),
        migrations.AddField(
            model_name='sample',
            name='fieldwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.fieldwork'),
            preserve_default=False,
        ),
    ]
