# Generated by Django 5.0.8 on 2025-08-12 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_locationvisit'),
        ('waterquality', '0018_remove_sample_location_visit_sample_fieldwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.location'),
        ),
    ]
