# Generated by Django 5.0.8 on 2025-08-13 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_delete_locationvisit'),
        ('waterquality', '0019_alter_sample_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='fieldwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='core.fieldwork'),
        ),
    ]
