# Generated by Django 5.0.8 on 2025-08-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0020_alter_sample_fieldwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('sample', 'parameter')},
        ),
        migrations.AddField(
            model_name='measurement',
            name='detection_limit_data',
            field=models.JSONField(blank=True, help_text='JSON field storing detection limit value and unit information', null=True),
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(blank=True, help_text='JSON field storing measurement value and unit information', null=True),
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='value',
        ),
    ]
