# Generated by Django 5.0.8 on 2025-08-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0021_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={},
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='created',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='created',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='modified',
        ),
        migrations.AlterField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(help_text='JSON field storing measurement value and unit information'),
        ),
    ]
