# Generated by Django 5.0.8 on 2025-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0022_alter_sample_options_remove_measurement_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(default=dict, help_text='JSON field storing measurement value and unit information'),
        ),
    ]
