# Generated by Django 5.0.8 on 2025-08-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterquality', '0023_alter_measurement_measurement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_data',
            field=models.JSONField(blank=True, default=dict, help_text='JSON field storing measurement value and unit information', null=True),
        ),
    ]
