# Generated by Django 5.0.14 on 2026-01-20 10:13

import django.db.models.deletion
import watersync.core.generics.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=55, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('detail', models.JSONField(blank=True, null=True)),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(choices=[('water_level', 'Water Level'), ('temperature', 'Temperature'), ('pressure', 'Pressure'), ('electrical_conductivity', 'Electrical Conductivity')], help_text='The variable being measured by this deployment', max_length=50)),
                ('unit', models.CharField(choices=[('kelvin', 'K (Kelvin)'), ('Pa', 'Pa (pascals)'), ('S/m', 'S/m (siemens per meter)'), ('bar', 'bar'), ('cm', 'cm (centimeters)'), ('cmH2O', 'cm H₂O (centimeters of water)'), ('ft', 'ft (feet)'), ('inch', 'in (inches)'), ('kPa', 'kPa (kilopascals)'), ('m', 'm (meters)'), ('mH2O', 'm H₂O (meters of water)'), ('mS/cm', 'mS/cm (millisiemens per cm)'), ('mbar', 'mbar (millibars)'), ('mm', 'mm (millimeters)'), ('psi', 'psi (pounds per square inch)'), ('degC', '°C (Celsius)'), ('degF', '°F (Fahrenheit)'), ('uS/cm', 'µS/cm (microsiemens per cm)')], help_text='Unit of measurement (must be valid for the selected variable)', max_length=50)),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.location')),
            ],
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
    ]
