# Generated by Django 5.0.8 on 2024-08-22 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=55, unique=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sensors',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployed_at', models.DateTimeField()),
                ('decommissioned_at', models.DateTimeField(blank=True, null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.sensor')),
            ],
            options={
                'verbose_name_plural': 'Sensor deployments',
                'unique_together': {('sensor', 'location', 'deployed_at')},
            },
        ),
        migrations.CreateModel(
            name='SensorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=8)),
                ('unit', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('flowrate', 'Flow rate'), ('pressure', 'Pressure'), ('temperature', 'Temperature'), ('volume', 'Volume')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sensor.deployment')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('deployment', 'timestamp', 'type')},
            },
        ),
    ]
