# Generated by Django 5.0.8 on 2024-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='deployed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
