# Generated by Django 5.0.8 on 2025-06-20 16:00

import watersync.core.generics.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
        migrations.AddField(
            model_name='sensor',
            name='variables',
            field=models.ManyToManyField(blank=True, help_text='Variables that this sensor can measure', to='sensor.sensorvariable'),
        ),
    ]
