# Generated by Django 5.0.8 on 2024-12-11 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
