# Generated by Django 5.0.14 on 2026-01-25 23:26

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fieldwork_options_remove_fieldwork_created_and_more'),
        ('sensor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='HistoricalDeployment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('variable', models.CharField(choices=[('water_level', 'Water Level'), ('temperature', 'Temperature'), ('pressure', 'Pressure'), ('electrical_conductivity', 'Electrical Conductivity'), ('dissolved_oxygen', 'Dissolved Oxygen'), ('ph', 'pH'), ('turbidity', 'Turbidity'), ('salinity', 'Salinity'), ('flow_rate', 'Flow Rate'), ('velocity', 'Flow Velocity'), ('rainfall', 'Rainfall'), ('humidity', 'Relative Humidity'), ('battery_voltage', 'Battery Voltage')], help_text='The variable being measured by this deployment', max_length=50)),
                ('unit', models.CharField(choices=[('percent', '%'), ('FNU', 'FNU (Formazin Nephelometric Units)'), ('kelvin', 'K (Kelvin)'), ('L/s', 'L/s (liters per second)'), ('NTU', 'NTU (Nephelometric Turbidity Units)'), ('PSU', 'PSU (Practical Salinity Units)'), ('Pa', 'Pa (pascals)'), ('S/m', 'S/m (siemens/meter)'), ('V', 'V (volts)'), ('atm', 'atm (atmospheres)'), ('bar', 'bar'), ('cm', 'cm'), ('cm/s', 'cm/s (centimeters per second)'), ('ft', 'ft (feet)'), ('ft/s', 'ft/s (feet per second)'), ('gpm', 'gpm (gallons per minute)'), ('inch', 'in (inches)'), ('kPa', 'kPa (kilopascals)'), ('m', 'm (meters)'), ('m/s', 'm/s (meters per second)'), ('mS/cm', 'mS/cm (millisiemens/cm)'), ('mV', 'mV (millivolts)'), ('mbar', 'mbar (millibars)'), ('mg/L', 'mg/L'), ('mm', 'mm'), ('m3/h', 'm³/h (cubic meters per hour)'), ('m3/s', 'm³/s (cubic meters per second)'), ('pH_unit', 'pH units'), ('ppt', 'ppt (parts per thousand)'), ('psi', 'psi (pounds per square inch)'), ('degC', '°C (Celsius)'), ('degF', '°F (Fahrenheit)'), ('uS/cm', 'µS/cm (microsiemens/cm)')], help_text='Unit of measurement (must be valid for the selected variable)', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, help_text='When this timeseries started', null=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='When this timeseries ended (null if ongoing)', null=True)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.location')),
                ('sensor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sensor.sensor')),
            ],
            options={
                'verbose_name': 'historical deployment',
                'verbose_name_plural': 'historical deployments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSensor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=55)),
                ('detail', models.JSONField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical sensor',
                'verbose_name_plural': 'historical sensors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
