# Generated by Django 5.0.14 on 2026-01-20 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='sensor.sensor'),
        ),
        migrations.AddField(
            model_name='sensorrecord',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sensor.deployment'),
        ),
        migrations.AlterUniqueTogether(
            name='deployment',
            unique_together={('sensor', 'location', 'variable', 'unit', 'deployed_at')},
        ),
        migrations.AlterUniqueTogether(
            name='sensorrecord',
            unique_together={('deployment', 'timestamp')},
        ),
    ]
