# Generated by Django 5.0.8 on 2025-02-19 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_alter_sensor_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
    ]
