# Generated by Django 5.0.14 on 2026-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
