# Generated by Django 5.0.8 on 2024-08-26 09:47

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensor_available_alter_deployment_deployed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='detail',
            field=django_jsonform.models.fields.JSONField(blank=True, null=True),
        ),
    ]
