# Generated by Django 5.0.14 on 2026-01-27 10:41

import django.db.models.deletion
import simple_history.models
import watersync.core.generics.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_sensorrecord_created_at_sensorrecord_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PressureSensorDeploymentDetail',
            fields=[
                ('deployment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pressure_sensor_detail', serialize=False, to='sensor.deployment')),
                ('installation_elevation', models.FloatField(help_text='Elevation of the sensor installation point in meters (above sea level or reference datum)', verbose_name='Installation Elevation (m)')),
            ],
            options={
                'verbose_name': 'Pressure Sensor Deployment Detail',
                'verbose_name_plural': 'Pressure Sensor Deployment Details',
            },
            bases=(models.Model, watersync.core.generics.models.SetupSimpleHistory),
        ),
        migrations.RemoveField(
            model_name='deployment',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='historicaldeployment',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='historicalsensor',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='detail',
        ),
        migrations.AddField(
            model_name='deployment',
            name='type',
            field=models.CharField(choices=[('gauge_pressure', 'Gauge Pressure'), ('absolute_pressure', 'Absolute Pressure'), ('other', 'Other')], default='other', help_text='The type of sensor deployment', max_length=20),
        ),
        migrations.AddField(
            model_name='historicaldeployment',
            name='type',
            field=models.CharField(choices=[('gauge_pressure', 'Gauge Pressure'), ('absolute_pressure', 'Absolute Pressure'), ('other', 'Other')], default='other', help_text='The type of sensor deployment', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='date_purchased',
            field=models.DateField(blank=True, help_text='The date when the sensor was purchased', null=True, verbose_name='Date Purchased'),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='The manufacturer of the sensor', max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='historicalsensor',
            name='model',
            field=models.CharField(blank=True, help_text='The model name/number of the sensor', max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='date_purchased',
            field=models.DateField(blank=True, help_text='The date when the sensor was purchased', null=True, verbose_name='Date Purchased'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='The manufacturer of the sensor', max_length=100, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='model',
            field=models.CharField(blank=True, help_text='The model name/number of the sensor', max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.CreateModel(
            name='HistoricalPressureSensorDeploymentDetail',
            fields=[
                ('installation_elevation', models.FloatField(help_text='Elevation of the sensor installation point in meters (above sea level or reference datum)', verbose_name='Installation Elevation (m)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('deployment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sensor.deployment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pressure Sensor Deployment Detail',
                'verbose_name_plural': 'historical Pressure Sensor Deployment Details',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
