# Generated by Django 5.0.8 on 2024-08-26 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='owner',
        ),
        migrations.AddField(
            model_name='sensor',
            name='user',
            field=models.ManyToManyField(related_name='sensors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='detail',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
