# Generated by Django 5.0.14 on 2026-01-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensorrecord_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='unit',
            field=models.CharField(choices=[('percent', '%'), ('FNU', 'FNU (Formazin Nephelometric Units)'), ('kelvin', 'K (Kelvin)'), ('L/s', 'L/s (liters per second)'), ('NTU', 'NTU (Nephelometric Turbidity Units)'), ('PSU', 'PSU (Practical Salinity Units)'), ('Pa', 'Pa (pascals)'), ('S/m', 'S/m (siemens/meter)'), ('V', 'V (volts)'), ('atm', 'atm (atmospheres)'), ('bar', 'bar'), ('cm', 'cm'), ('cm/s', 'cm/s (centimeters per second)'), ('ft', 'ft (feet)'), ('ft/s', 'ft/s (feet per second)'), ('gpm', 'gpm (gallons per minute)'), ('inch', 'in (inches)'), ('kPa', 'kPa (kilopascals)'), ('m', 'm (meters)'), ('m/s', 'm/s (meters per second)'), ('mS/cm', 'mS/cm (millisiemens/cm)'), ('mV', 'mV (millivolts)'), ('mbar', 'mbar (millibars)'), ('mg/L', 'mg/L'), ('mm', 'mm'), ('m3/h', 'm³/h (cubic meters per hour)'), ('m3/s', 'm³/s (cubic meters per second)'), ('pH_unit', 'pH units'), ('ppt', 'ppt (parts per thousand)'), ('psi', 'psi (pounds per square inch)'), ('degC', '°C (Celsius)'), ('degF', '°F (Fahrenheit)'), ('uS/cm', 'µS/cm (microsiemens/cm)')], help_text='Unit of measurement (must be valid for the selected variable)', max_length=50),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='variable',
            field=models.CharField(choices=[('water_level', 'Water Level'), ('temperature', 'Temperature'), ('pressure', 'Pressure'), ('electrical_conductivity', 'Electrical Conductivity'), ('dissolved_oxygen', 'Dissolved Oxygen'), ('ph', 'pH'), ('turbidity', 'Turbidity'), ('salinity', 'Salinity'), ('flow_rate', 'Flow Rate'), ('velocity', 'Flow Velocity'), ('rainfall', 'Rainfall'), ('humidity', 'Relative Humidity'), ('battery_voltage', 'Battery Voltage')], help_text='The variable being measured by this deployment', max_length=50),
        ),
    ]
