# Generated by Django 5.0.8 on 2025-03-10 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_alter_sensor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deployment',
            options={},
        ),
    ]
