# Generated by Django 5.0.8 on 2025-03-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_alter_deployment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={},
        ),
    ]
