# Generated by Django 5.0.8 on 2025-03-26 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_historicallocation'),
        ('sensor', '0005_alter_sensor_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='core.location'),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='sensor.sensor'),
        ),
    ]
