# Generated by Django 5.0.8 on 2024-08-29 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_alter_sensorrecord_deployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorrecord',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='sensor.deployment'),
        ),
    ]
