# Generated by Django 5.0.8 on 2025-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0006_alter_deployment_location_alter_deployment_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('vented', 'Vented'), ('unvented', 'Unvented'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
