# Generated by Django 5.0.8 on 2024-11-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWLManualMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.location')),
            ],
            options={
                'verbose_name_plural': 'Groundwater level - manual measurements',
                'unique_together': {('location', 'timestamp')},
            },
        ),
    ]
