# Generated by Django 5.0.14 on 2026-01-20 10:13

import django.db.models.deletion
import django_extensions.db.fields
import watersync.core.generics.interfaces
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GWLManualMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('depth', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('fieldwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwlmeasurements', to='core.fieldwork')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.location')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=(models.Model, watersync.core.generics.interfaces.InterfaceModelTemplate),
        ),
    ]
