# Generated by Django 5.0.8 on 2024-12-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_locationstatus_location'),
        ('groundwater', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwlmanualmeasurements',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.location'),
        ),
    ]
