# Generated by Django 5.0.14 on 2026-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwlmanualmeasurement',
            options={'ordering': ['-fieldwork__date']},
        ),
        migrations.RemoveField(
            model_name='gwlmanualmeasurement',
            name='depth',
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
