# Generated by Django 5.0.14 on 2026-01-26 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historicalproject_is_active_and_more'),
        ('groundwater', '0002_remove_gwlmanualmeasurement_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwlmanualmeasurement',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.location'),
            preserve_default=False,
        ),
    ]
