# Generated by Django 5.0.14 on 2026-01-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
        ('groundwater', '0002_alter_gwlmanualmeasurement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwlmanualmeasurement',
            name='fieldwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.fieldwork'),
        ),
    ]
