# Generated by Django 5.0.8 on 2024-12-11 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_locationstatus_location'),
        ('groundwater', '0002_alter_gwlmanualmeasurements_location'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GWLManualMeasurements',
            new_name='GWLManualMeasurement',
        ),
    ]
