# Generated by Django 5.0.8 on 2025-03-10 21:19

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0003_rename_gwlmanualmeasurements_gwlmanualmeasurement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gwlmanualmeasurement',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AlterUniqueTogether(
            name='gwlmanualmeasurement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='measured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='gwlmanualmeasurement',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='gwlmanualmeasurement',
            name='timestamp',
        ),
    ]
