# Generated by Django 5.0.8 on 2025-03-31 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groundwater', '0004_alter_gwlmanualmeasurement_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gwlmanualmeasurement',
            old_name='comment',
            new_name='description',
        ),
    ]
