# Generated by Django 5.0.8 on 2025-04-15 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_locationvisit_slug_locationvisit_date'),
        ('groundwater', '0005_rename_comment_gwlmanualmeasurement_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwlmanualmeasurement',
            name='location',
        ),
        migrations.RemoveField(
            model_name='gwlmanualmeasurement',
            name='measured_at',
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='location_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.locationvisit'),
        ),
    ]
