# Generated by Django 5.0.8 on 2025-08-12 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_locationvisit_fieldwork_and_more'),
        ('groundwater', '0006_remove_gwlmanualmeasurement_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwlmanualmeasurement',
            name='location_visit',
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='fieldwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gwlmeasurements', to='core.fieldwork'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gwlmanualmeasurement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gwlmeasurements', to='core.location'),
        ),
    ]
